import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BO.KE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://bo.ke">BO.KE</a>
        </h1>

        <p className={styles.description}>
          服务器被孤儿攻击打到自动销毁了{' '}
          <code className={styles.code}>祝他早日登天</code>
        </p>

        <div className={styles.grid}>
          <a href="https://loc.cc" className={styles.card}>
            <h2>非主流论坛</h2>
            <p>来论坛一起谴责这个DDOS的孤儿.</p>
          </a>

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://bo.ke"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            BO.KE
          </span>
        </a>
      </footer>
    </div>
  )
}
